/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package data.ui;

import data.ui.lib.Database;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import data.ui.Ngrams;
import java.util.ArrayList;
import java.math.*;
import java.util.HashMap;
/**
 *
 * @author Dosen
 */
public class Form_Ngrams extends javax.swing.JFrame {

    /**
     * Creates new form Form_Tweet
     */
    Database dbsetting;
    String driver, database, user,pass;
    public HashMap<String, Float> dfidftMap;
    public Form_Ngrams() {//konstruktor
        initComponents();
        dbsetting = new Database();
        driver = dbsetting.SettingPanel("DBDriver");
        database = dbsetting.SettingPanel("DBDatabase");
        user = dbsetting.SettingPanel("DBUsername");
        pass = dbsetting.SettingPanel("DBPassword");
        this.setSize(1000, 700);
        tblModel = getDefaultTabelModel(); // Inisialisasi tabel model
        tabel.setModel(tblModel);
        Tabel(tabel, new int[]{120, 180, 120, 120, 700});

        dfidftMap = new HashMap<>(); // Inisialisasi HashMap untuk DF-IDFT
        setDefaultTable();
        
      
    }
    
    public void simpanTabel(String ngrams, float dfidft, int timeslots) {
        dfidftMap.put(ngrams, dfidft);

        try{
           Class.forName(driver);
           Connection kon = DriverManager.getConnection(database, user, pass);
           Statement stt = kon.createStatement();
           String SQL = "insert into tb_ngrams(n_grams, dfidft, timeslots) "
                   + "values ('"+ngrams+"','"+dfidft+"','"+timeslots+"')";
           System.out.println("SQL = "+SQL);
           stt.executeUpdate(SQL);
           stt.close();
           kon.close();
        } catch(Exception e) {
            System.err.println("Error: " + e.getMessage());
        }
    }
    
    
    
    public void setDefaultTable() {
     int jumkata=0,dfi=0,dfi_j=0;
    try {
        Class.forName(driver);
        Connection kon = DriverManager.getConnection(database, user, pass);
        Statement stt = kon.createStatement();
        String SQL = "SELECT * FROM tb_ngrams";
        System.out.println("Executing query: " + SQL);
        ResultSet res = stt.executeQuery(SQL);
       // "Created At","Time Slots","ID Tweets","Text","Bigrams"
        String[] data = new String[5];
        while (res.next()) {
            data[0] = res.getString("id");
            data[1] = res.getString("n_grams");
            data[2] = res.getString("dfidft");
            data[3] = res.getString("timeslots");
            data[4] = res.getString("nilai_terbesar");

//isi kalimat tweet
            /// loop perbaris utk cek kemunculan n-grams pada timeslots 1///
            tblModel.addRow(data);
           
           System.out.println("=========================================");

        }
        res.close();
        stt.close();
        kon.close();
    } catch (Exception e) {
        System.err.println("Error: " + e.getMessage());
        e.printStackTrace(); // Print full stack trace for debugging
    }
}   
    
    private void Tabel(javax.swing.JTable tb, int lebar[]){
        tb.setAutoResizeMode(tb.AUTO_RESIZE_OFF);
        int kolom = tb.getColumnCount();//dapatkan jumlah kolom
        for(int i=0;i<kolom;i++){
            javax.swing.table.TableColumn tbc = tb.getColumnModel().getColumn(i);
            tbc.setPreferredWidth(lebar[i]);//lebar per kolom
            tb.setRowHeight(17);//lebar per baris
        }
    }
    private javax.swing.table.DefaultTableModel getDefaultTabelModel(){
        return new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{"Id","N-grams","Dfidft","Timeslots","Nilai terbesar"}
        ){
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false
            };
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return canEdit[columnIndex];
            }
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "N-grams", "Dfidft", "Timeslots", "Nilai terbesar"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 840, 190);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROGRAM DETEKSI TRENDING TOPIC (DF-IDFT)");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 30, 470, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Ngrams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Ngrams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Ngrams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Ngrams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Ngrams().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
private javax.swing.table.DefaultTableModel tblModel = getDefaultTabelModel(); 
}
